---
name: 'Terraform'

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions
    # runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          # renovate: datasource=github-tags depName=hashicorp/terraform versioning=loose
          terraform_version: 1.8.5

      # Initialize a new or existing Terraform working directory by
      # creating initial files, loading any remote state, downloading
      # modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a
      # canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Checks that Terraform configuration is valid
      - name: Terraform Validate
        run: terraform validate
